### ISSUE TITLE
.oni files are read 2 times slower.

### ISSUE THREAD

**Issue by totoetlititi** [diablodale/jit.openni#11]
With OSX 10.6.8, Max 5.1.9, version_jit.openni 0 8 6, version_openni 1 5 4 0 :

Hi,

When a .oni file is read thru jit.openni, video is 2 times slower than the original.
You can see it with skeletonrec.oni & jit.openni_debugrec.xml. 
Or if you do a record with NiViewer application.

An extra request :  how navigate inside video ? like jumping to a given position ?

Thanks !
_TG

**Comment by diablodale** [comment]
From what I can determine, this is a fault in OpenNI itself. I can reproduce the same behavior using only the OpenNI samples binaries. Try this yourself:
1) install a working Kinect
2) Use the NiViewer application to record a 20 second clip. Do something very obvious that can be timed like waving your finger in 1 second intervals. I did this watching a stopwatch.
3) close NiViewer
4) run NiViewer and on the commandline, give it the filename of the recording you just made
5) watch the results
The playback is too slow. My estimation is that it is 1.5x too slow.

Do you reproduce this problem give my steps above? If so, then this is a bug in the OpenNI code and not one that I can fix. You can, however, workaround the issue in your own patch. When you have a recording loaded, bang jit.openni approximately 1.5x faster. In the demo patch I provide, I banged it at 22ms (which is about 45fps)

**Comment by totoetlititi** [comment]
Exactly, same problem with NiViewer.
But what I see is more complex, speed seems variable : some parts of the video is very slower, and some part just a bit slower...
In this case, changing bang speed is not a valid trick !

**Comment by diablodale** [comment]
Unfortunately, this is a bug in OpenNI itself. I am not able to fix this. I don't control the code, they do.
If you would like, you can get the source code for OpenNI, debug this issue, fix it, and compile it yourself. However, I don't recommend it.

If you are on Windows, I recommend you use dp.kinect instead. The Microsoft Kinect SDK is far more reliable and therefore the external benefits from it.

I may be able to give you advice or a recommendation if I better understand your need for accurate time playback of ONI files. Would you share that?

**Comment by diablodale** [comment]
I am closing this issue as the bug is external (PrimeSense's bug) and they are not going to fix it.

If you feel I have not addressed your concern, please reopen this issue
