### ISSUE TITLE
Set the user timeout?

### ISSUE THREAD

**Issue by aartcore** [diablodale/jit.openni#13]
Hey Diablodale,

Is it possible to set the time which the openni is keep looking for a lost user. 
For example when somebody goes stand for an existing user it takes about 15 seconds before this existing user is lost. 
I'm using the image of only the first two 'active' users, but now i get sometimes for about 15 seconds a black output because the user isn't lost yet. The exituser and reenter functions won't work if someone stand for another person. 

I would be great if you can set this time directly in the jit.openni

I found some thread on the OpenNI forum:
https://groups.google.com/forum/#!msg/openni-dev/OCV_BiVJrng/MPwb-q_01LQJ
 (i don't know if the link is usefull or not)

Thanks in advance,

Aart

**Comment by diablodale** [comment]
Interesting inquiry. Unfortunately, there is no known way to change the timeout for recognizing users (aka skeletons) on the lost/re-enter/exit.

The OpenNI SDK writes, "The 'Lost User' event signals that a user has been lost from the list of previously recognized users in the scene. The exact meaning of a 'lost user' is decided by the developer of the xn::UserGenerator. However, a typical implementation would define that a lost user is a previously recognized user that then exits the scene and does not return, even after a 'Lost User' timeout has elapsed. Thus this event might be raised only after some delay after the user actually exited the scene."

PrimeSense writes OpenNI and NITE. NITE is the user generator portion of that. PrimeSense did not expose a way to change the timeouts that you need. :-/

The link you provided to the forum writes about the timeout for gesture recognition. NITE also provides functionality for gesture recognition and in that API set, they _did_ expose a method to control the timeout. Unfortunately, they did not expose a method for user/skeletons recognition.

This will not change for the current v1.x SDK. PrimeSense has abandoned that SDK and completely re-written everything for a v2 SDK which is still in early development.

As a suggestion (I don't know much about your project) you might have better results by using the users who are "moving" or users which are the closest to the Kinect. When a user exits, you will get the exit event and their coordinate values should change very little (or not at all). Using a combination of looking at the exit event + users who's coordinates are unchanging can likely tell you which users should be removed from your scene. The users that remain, are the users who are actively moving and you are probably most interested in.

If you believe I have not addressed your concern, please reopen this issue.
