### ISSUE TITLE
Mapping & extract single  users 

### ISSUE THREAD

**Issue by Vllrich** [diablodale/jit.openni#14]
I'm mapping the jit.openni output to a jitter matrix and I'm wondering what would be the z range in pixels?

x = 0. 640. 1. -1.
y = 0. 480. 1. -1.
z = 0. 1400. -1. 1. ??

Also is there a way to extract the single/multiple user?

Thanks!

**Comment by diablodale** [comment]
There is no z range in pixels. PIxels are in a 2-dimensional space, there is no z. Only X and Y.

**Comment by Vllrich** [comment]
thanks for that! I thought the depth map will take care of that.

What about the single user mode, is this feature working?

**Comment by diablodale** [comment]
I do not know what you mean by single user mode. There is no feature in the SDK that I know by that name.
Have you read the wiki documentation? It is in the menu bar at the top. It describes all the features that are currently implemented.

**Comment by diablodale** [comment]
I'm closing this issue due to no response. If you have a future specific issue/problem, please open a new issue.
