### ISSUE TITLE
IR map output not working

### ISSUE THREAD

**Issue by imklif** [diablodale/jit.openni#15]
Hi,

I tried to edit jit.openni_config file to turn on IR map output, but it doesn't work for me. I get 
jit_openni: XML config initialization open failed (Bad Parameter sent to the device!)
error in max window. I also tried changing framerate parameter to 60 with the same result. I'm on osx 10.7.5, Max 6.0.8, Microsoft Kinect.

Klif

Here is my non-working config file:

<OpenNI>
   <ProductionNodes startGenerating="true">
    <Node type="Image" name="Image1" stopOnError="false">
      <Configuration>
        <Mirror on="true" />
      </Configuration>
    </Node>

```
<Node type="IR" name="Ir1">
  <Configuration>
    <MapOutputMode xRes="320" yRes="240" FPS="30"/>
    <Mirror on="true"/>
  </Configuration>
</Node>

<Node type="Depth" name="Depth1">
    <Configuration>
        <AlternativeViewPoint>Image1</AlternativeViewPoint>
        <Mirror on="true" />
    </Configuration>
</Node>

<Node type="User" name="User1" />
```

  </ProductionNodes>
</OpenNI>

**Comment by diablodale** [comment]
Several questions I have for you.
1. Does the kinect work when you use the jit.openni_config.xml file and jit.openni_test1.maxpat?
If it does work, then there is likely a problem with your installation or with your customized XML file. OpenNI is very bug ridden and they are not fixing the bugs (they abandoned the codebase). I suggest you use the specific IR settings that I have in the jit.openni_config.xml file (they are commented out).
2. If (1) doesn't work, then do the sample applications that are distributed in the Sample folder of the OpenNI installation work?
If they don't work, then there is something code wrong with your installation, computer, other other unknown issue.

Write me back with your results

**Comment by imklif** [comment]
hi,

kinect works with both files, i simply commented out IR bit of jit.openni_config.xml. 

as far as I remember i downloaded a package suggested in a thread on cycyling74 forum. it was for some gaming package, and included all the libraries in a single installer. maybe it has to do with that.

klif

**Comment by diablodale** [comment]
It might. Unfortunately, I am not able to support a setup that both I and you don't know about.
I'm closing this issue as an unknown and potentially setup related issue.

**Comment by diablodale** [comment]
On 2nd thought, I recommend you wipe and reinstall your OS and then follow the installation procedure that I provide in the setup documentation. This setup documentation is the same that OpenNI provides in their official distribution.

If you are unable to wipe and reinstall your OS, then remove all traces of this unknown other setup package. Remove all libraries, i ncludes, DLLs, dynamic libraries, XML files, configuration files, EVERYTHING. If you are not able to remove everything, then you now have your computer in an unknown state and it is difficult to troubleshoot anything.

**Comment by imklif** [comment]
Hi Dale,

Sorry for the confusion, I just couldn't remember the name of the package. It is from www.zigfu.com
Installer says it includes:

libusb-devel universal build
PrimeSense NITE: 1.5.2.21
OpenNI: 1.5.4.0
Sensor: 5.1.2.1 (ASUS Xtion driver)
SensorKinect: 5.1.2.1
ZigJS: 1.0.1b

**Comment by imklif** [comment]
FYI, I installed the zigfu package and jit.openni.mxo on 2 computers, and they performed flawlessly for a month of theatre production. I was using almost everything else except IR image.

If it works for you, there is probably something wrong with my installation. From what I saw in cycling74 forums, many people have problems getting it right with all the installer packages. I just wanted to see if I did something wrong with the edited config file (it seems it didn't paste well in my first comment, but it is the original jit.openni_config.xml - i just commented-out the IR bit)

P.S. for some reason the whole config file doesn't show in this post. When I'm editing the post, the whole thing is here, but when i press "Comment" or "Update comment", half of it disappears again. Anyway, the IR part is visible anyway, The beginning ant the end are missing, but they are identical to the original config file.

<OpenNI>

   <ProductionNodes startGenerating="true">
    <Node type="Image" name="Image1" stopOnError="false">
      <Configuration>
        <Mirror on="true" />
      </Configuration>
    </Node>

```
<Node type="IR" name="Ir1">
  <Configuration>
    <MapOutputMode xRes="320" yRes="240" FPS="30"/>
    <Mirror on="true"/>
  </Configuration>
</Node>

<Node type="Depth" name="Depth1">
    <Configuration>
        <AlternativeViewPoint>Image1</AlternativeViewPoint>
        <Mirror on="true" />
    </Configuration>
</Node>

<Node type="User" name="User1" />
```

  </ProductionNodes>
</OpenNI>

**Comment by diablodale** [comment]
I am aware of Zigfu but do not recommend or have an opinion on it. Installing Zigfu instead of the official method from OpenNI may led to unpredictable problems which I am not able to support.

Try this series of XML instead the ProductionNodes
`
    <Node type="IR" name="IR1">
        <Configuration>
            <MapOutputMode xRes="640" yRes="480" FPS="30"/>
            <Mirror on="true"/>
        </Configuration>
    </Node>
    <Node type="Depth" name="Depth1">
        <Configuration>
            <Mirror on="true" />
        </Configuration>
    </Node>
    <Node type="User" name="User1" />`

**Comment by diablodale** [comment]
closing due to no response
