### ISSUE TITLE
Skeletonrec.oni

### ISSUE THREAD

**Issue by ninosgr** [diablodale/jit.openni#16]
Hi there, 

Thanks for this amazing work !!

unfortunately I cannot find the skeletonrec.oni file to download the link
http://openni.org/downloads/skeletonrec.oni

does not exist anymore and I cant even find it anywhere else only

Despite that everything seems to work fine (although I have not track anything yet)

Do I really need this file? is there an alternative?

Thanks,
Ninos

**Comment by aartcore** [comment]
It's a file if you want to test without using the kinect, can be very usefull:
http://www.aartvinding.nl/x/skeletonrec.oni

on this link someone put more oni files to test with:
http://www.jvcref.com/files/oni/?C=S;O=A

is there anyone know how to record these oni files?

**Comment by diablodale** [comment]
Thanks for reporting this. I have also uploaded the file to http://hidale.com/wp-content/uploads/2012/09/skeletonrec.oni

The next updated to jit,openni will have a new demo patcher that also use this new location.
