### ISSUE TITLE
Connection with PMD Camboard nano depth sensor

### ISSUE THREAD

**Issue by vagelisde** [diablodale/jit.openni#17]
I have downloaded and used jit.openni And it’s really amazing and very useful combined with kinect. I have created an application in max/msp in which I use kinect to get data. I have the PMD Camboard nano depth sensor and i have already connect it with the openni. I would like to know if i can use your jit.openni with this specific depth sensor. I have already tried to connect it but without any results. What could I do to make it work. Any help would be appreciated.

Thanks

**Comment by vagelisde** [comment]
Also i want to inform you that when i try to run the application with camboard nano i have only one error : 
"XML config initialization open faild (the device not connected)"

**Comment by diablodale** [comment]
First, you will need an OpenNI 1.x compliant driver for the PMD. If this driver is compliant, then you will be able to configure the XML file to attach to this device. I provide an XML file which queries for and attached to any sensor that matches the query. That's how the XML work...it queries for any device that matches the needs and then attaches to it. The XML specification is part of the OpenNI 1.x SDK which you can still download from their website. You can probably also just real the XML file itself and figure it out.

I think a good thread to read is this
https://www.cayim.com/forum/index.php?/topic/117-openni-sample-module/

It describes PMD files that you need to download and install. It looks like you have to do some manual configuration by editing that modules.xml file.
I recommend you also adjust the XML configuration file so that you only have a <depth> node. No <image>. No <user>. Try to get it working with just that.

Please do reply back with your progress here so that others can also learn.

**Comment by vagelisde** [comment]
Hi again,
Thank you very much for your direct reply!
I have already run the openni sample module from https://www.cayim.com/forum/index.php?/topic/117-openni-sample-module/ and it works ok. Also i have deleted the kinect sensor module from modules.xml file and create a module for pmdSample.dll. 
this is modules.xml after the editing:

<Modules>
    <Module path="C:\Program Files\OpenNI\bin\nimRecorder.dll" />
    <Module path="C:\Program Files\OpenNI\bin\nimMockNodes.dll" /> 
    <Module path="C:\Program Files\OpenNI\bin\nimCodecs.dll" />
    <Module path="C:\Users\Administrator\Desktop\PMD_Example\CamboardNano_OpenNISampleModule\Debug\PMDSampleModule.dll" />



```
<Module path="C:\Program Files\PrimeSense\NITE\Features_1_3_0\Bin\XnVFeatures_1_3_0.dll" configDir="C:\Program Files\PrimeSense\NITE\Features_1_3_0\Data" />
<Module path="C:\Program Files\PrimeSense\NITE\Features_1_3_1\Bin\XnVFeatures_1_3_1.dll" configDir="C:\Program Files\PrimeSense\NITE\Features_1_3_1\Data" />
<Module path="C:\Program Files\PrimeSense\NITE\Features_1_4_1\Bin\XnVFeatures_1_4_1.dll" configDir="C:\Program Files\PrimeSense\NITE\Features_1_4_1\Data" />
<Module path="C:\Program Files\PrimeSense\NITE\Features_1_4_2\Bin\XnVFeatures_1_4_2.dll" configDir="C:\Program Files\PrimeSense\NITE\Features_1_4_2\Data" />
<Module path="C:\Program Files\PrimeSense\NITE\Features_1_5_2\Bin\XnVFeatures_1_5_2.dll" configDir="C:\Program Files\PrimeSense\NITE\Features_1_5_2\Data" />
<Module path="C:\Program Files\PrimeSense\NITE\Hands_1_3_0\Bin\XnVHandGenerator_1_3_0.dll" configDir="C:\Program Files\PrimeSense\NITE\Hands_1_3_0\Data" />
<Module path="C:\Program Files\PrimeSense\NITE\Hands_1_3_1\Bin\XnVHandGenerator_1_3_1.dll" configDir="C:\Program Files\PrimeSense\NITE\Hands_1_3_1\Data" />
<Module path="C:\Program Files\PrimeSense\NITE\Hands_1_4_1\Bin\XnVHandGenerator_1_4_1.dll" configDir="C:\Program Files\PrimeSense\NITE\Hands_1_4_1\Data" />
<Module path="C:\Program Files\PrimeSense\NITE\Hands_1_4_2\Bin\XnVHandGenerator_1_4_2.dll" configDir="C:\Program Files\PrimeSense\NITE\Hands_1_4_2\Data" />
<Module path="C:\Program Files\PrimeSense\NITE\Hands_1_5_2\Bin\XnVHandGenerator_1_5_2.dll" configDir="C:\Program Files\PrimeSense\NITE\Hands_1_5_2\Data" />
<Module path="C:\Program Files\PrimeSense\Sensor\Bin\XnDeviceFile.dll" />   
```

<Module path="C:\Program Files\PrimeSense\Sensor\Bin\XnDeviceSensorV2.dll" configDir="C:\Program Files\PrimeSense\Sensor\Data" /> 

</Modules>

The NiViewer.exe run correctly with pmd, but when i try to run my app doesn't play.
I have tried to edit your xml config file and opnni xml config file but without any results
There is anything else which i can do? 
The error which appears now is 
"XML config initialization open failed (This operation is invalid!)"

Thank you a lot for your time

**Comment by diablodale** [comment]
The modules.xml you past above does not have the pmd module in it. It will not work without the pmd module in it.
Have you read the XML documentation in the OpenNI SDK? It can guide you as to changes you might need to make to the XML file.

Please paste in your XML file here with your changes and I can review it. Perhaps I can see a problem.

**Comment by vagelisde** [comment]
Yesterday i pasted all line from modules.xml but apeared only a few lines. I don't understand why...sorry about that

```
<Module path="C:\Program Files\OpenNI\bin\nimRecorder.dll" />
<Module path="C:\Program Files\OpenNI\bin\nimMockNodes.dll" /> 
<Module path="C:\Program Files\OpenNI\bin\nimCodecs.dll" />
<Module path="C:\Users\Administrator\Desktop\PMD_Example\CamboardNano_OpenNISampleModule\Debug\PMDSampleModule.dll" />
<!-- <Module path="C:\Program Files\PrimeSense\SensorKinect\Bin\XnDeviceFile.dll" />
<Module path="C:\Program Files\PrimeSense\SensorKinect\Bin\XnDeviceSensorV2KM.dll" configDir="C:\Program Files\PrimeSense\SensorKinect\Data" /> -->
```

 path="C:\Program Files\PrimeSense\Sensor\Bin\XnDeviceSensorV2.dll" configDir="C:\Program Files\PrimeSense\Sensor\Data" 

thanks

**Comment by vagelisde** [comment]
I can't paste all lines together.
The two comments above include all lines of xml file 

Tell me i f you want something other

**Comment by diablodale** [comment]
It is unfortunate that the PMD driver doesn't install and configure this for you. I am unsure what to do...I have no way to test it.

It looks like you have removed a lot from the file (where are all the NITE modules)?
Try and remove only the two SensorKinect lines + remove the C:\Program Files\PrimeSense\Sensor\Bin\XnDeviceSensorV2.dll line

Then you still need to edit the XML configuration file that is in the same folder as your patch. It will likely not work until that is edited. Change it so there is only the <depth> node with no configuration like "mirror" inside it. Try this:

```
<OpenNI>
  <ProductionNodes startGenerating="true">
    <Node type="Depth" name="Depth1">
    </Node>
  </ProductionNodes>
</OpenNI>
```

That will only enable the depth node and its output. Do not try to enable image/color output in your patch or it will fail.

**Comment by vagelisde** [comment]
It works!! Thank you a lot for your help.
It's great!!
You seved me from a lot of trouble.

**Comment by diablodale** [comment]
Good news. By editing the config.xml in the same directory as your patch and loading it in the patcher, you may be able to configure more options for the PMD sensor. For example, you might be able to mirror the image, get the raw IR feed, etc.
