### ISSUE TITLE
setting asus xtion pro live

### ISSUE THREAD

**Issue by carsol-xx** [diablodale/jit.openni#18]
Im trying to setup an Asus Xtion PRO live with your jit.openni external with max6 in osx 10.8.3 
i installed the soft and exact versions you mention in your wiki and with a Xbox Kinect works fine but when i plug the Xtion jit.openni says no camera detected.

Then i install OpenNI v2 and the Xtion camera is well detected but the system and i get depth image with SimpleViewer program but then jit.openni give this error:

jit.openni: unable to load object bundle executable
 2013-03-28 09:48:38.730 Max[243:c07] Error loading /Users/oscar/Documents/max/externalsMAC/JitOpenni/jit.openni.mxo/Contents/MacOS/jit.openni:  dlopen(/Users/oscar/Documents/max/externalsMAC/JitOpenni/jit.openni.mxo/Contents/MacOS/jit.openni, 262): Library not loaded: ../../Bin/x64-Release/libOpenNI.dylib
   Referenced from: /Users/oscar/Documents/max/externalsMAC/JitOpenni/jit.openni.mxo/Contents/MacOS/jit.openni
   Reason: image not found

did you know how i can solve this? the missing library?

thank you very much!

**Comment by diablodale** [comment]
jit.openni is based on the v1.x generation of OpenNI. You will need v1.x compatible drivers for your Xtion + the v1.x generation of the OpenNI/NITE stack + libusb.

The v2 generation of drivers and OpenNI/NITE stack will not function. Unfortunately, OpenNI abandoned v1.x with no migration or backward compatibility story. :-/

I have read of people using jit.openni with Kinect, Asus, and the PMD Camboard. The major problems seem to occur with getting the right hardward driver (e.g. for your Asus) and the XML configuraiton file correct (as the drivers can be particular in the method you query for them).

I looked at the Asus site I link below. I don't even see drivers for a Mac. Where are you getting v1 hardware drivers for your Xtion Pro?
http://support.asus.com/Download.aspx?SLanguage=en&m=Xtion%20PRO%20LIVE&p=19&s=11

As far as teh config file. Make it very very simple and them add more feature in as you get the simple case working. One of the simplest would be to only ask for a depthmap with the following:

```
<OpenNI>
  <ProductionNodes startGenerating="true">
    <Node type="Depth" name="Depth1">
    </Node>
  </ProductionNodes>
</OpenNI>
```

**Comment by carsol-xx** [comment]
ok, good to know the incompatibility between OpenNI v2 and jit.openni.. what a pity, because at least on my system, only the v2 handle the Xtion good, giving back depth image with SimpleViewer...

with OpenNI 1.5.4 SimpleViewer says:

Device: PrimeSense/SensorKinect/5.1.2.1: The device is not connected!

and jit.openni says more or less the same...

sorry for the misunderstanding, i didn't download any asus driver... osx detects the camera straight forward.

thanks diablo!

**Comment by diablodale** [comment]
There is a specific driver that should be loaded on the Mac to enable the Xtion. Osx will not by default have drivers for the depth camera. (Maybe it does for the RGB but definitely not the depth).
If you have installed OpenNI v2 binaries, drivers, etc, then you should remove all traces of them so that they are not accidentially loaded instead of the v1 codebase.

I know people have been using the Xtion pro with OpenNI v1. I see it googling for related results and see applications supporting that configuration. I don't however, see where people are getting the drivers from. Take a look at the following three and try their approach.
http://answers.ros.org/question/54747/primesense-carmine-doesnt-work-but-asus-xtion-does-openni-launch-devices-connected-but-not-found/
http://answers.ros.org/question/50325/can-not-use-xtion-pro-live/
http://www.openni.org/openni-sdk/openni-sdk-history-2/#.UVswYpMSZ8E

**Comment by carsol-xx** [comment]
> There is a specific driver that should be loaded on the Mac to enable the Xtion. Osx will not by default have drivers >for the depth camera. (Maybe it does for the RGB but definitely not the depth).
> 
> you mean that using OpenNI 1.5.4 i need a specific driver also?
> with OpenNI2 i get depth image with SimpleViewer straight forward without any specific driver....

i keep goggling...

thanks

**Comment by diablodale** [comment]
All hardware needs an OpenNI compliant hardware driver.
PrimeSense created OpenNI and a sensor (commonly called the PrimeSense sensor). They distributed their hardware driver in the same package as OpenNI,
A Kinect driver was not included in that package, so you have to download/install SensorKinect.
I do not know where the Xtion Pro driver is. The Asus website has downloads for LOTS of operating systems except for Mac OSx. it is very odd.

**Comment by diablodale** [comment]
closing this issue due to no response and the issue appears to be the lack of a functioning driver for the Xtion Pro.
