### ISSUE TITLE
jit.openni and max6.1.1 (jit_linklist_chuckptr error)

### ISSUE THREAD

**Issue by sqrtmo** [diablodale/jit.openni#19]
Hello, yesterday I found that jit.openni doesn't work in max 6.1.1 on my computer.
I try it, and it works in max 5.1.9 and 6.0.8.

osx 10.7.5
jit.openni 0.7.8

Max can not load jit.openni object, I have this message.
![Screen Shot 2013-04-09 at 10 54 33 AM](https://f.cloud.github.com/assets/3294483/355722/9e7c1d2a-a0eb-11e2-8ed9-0f5ab808fbf9.png)

**Comment by diablodale** [comment]
You will need to update to version jit.openni v0.88
Max 6 removed an API that I was using and v0.88 resolved that issue. You can download from the normal http://hidale.com/jit-openni/

Please reply back here after you upgrade so that we confirm it is resolved.

**Comment by sqrtmo** [comment]
Thanks a lot!

**Comment by sqrtmo** [comment]
Ok, working!:) thanks again.
