### ISSUE TITLE
kinect strange behavior

### ISSUE THREAD

**Issue by sqrtmo** [diablodale/jit.openni#22]
Hello, 
I have problems with behavior of my installation in a hall where it is now.
I have never seen this behavior before, it founds people when there is nobody in front of the kinect. And the opposite, some times it can not see no one when it should. 
I had installed this project several times before in different places and it was working fine.
I have checked every thing in my max patch a couple of times and there are no mistakes. Some times I see that jit.openni founds skeletons and they walking inside the kinect working aria, but with out no persons there.
I don't know where to look for the reason. What is the probability that PIR sensors for alarm installations can be the problem?
If anyone have similar experience please share.

**Comment by diablodale** [comment]
I have read that infrared interference from other sources can affect the Kinect. I know of no solution other than to get away from the interference.

**Comment by sqrtmo** [comment]
Thanks for a replay
Ok, I have searched, and found that many of types ired distance sensors for example, have а protection from other infrared light sources the source light is not a constant, it have some frequency, and the receiver is programed to read only that frequency. 
It looks like the kinect don't have such protection or I can not fond nothing about this.
When I have my kinect back I will try it in a sunny room:)

**Comment by diablodale** [comment]
closing as this is a problem external to jit.openni.
It is IR interference in the environment.
