### ISSUE TITLE
Body Relative

### ISSUE THREAD

**Issue by joncorcu** [diablodale/jit.openni#26]
Hi!

I´m immerse in a project where i want to use only the hands to control certain parameters. But I need this points to be body relative, not world relative.

I´m doing some tests but i can't figure out how to do this process. 

If someone has already done this work or knows how to do it, would be very helpful.

Thanks for the great job Dale!

**Comment by adrianfreed** [comment]
Body Relative is a tricky concept. What part of the body is your origin? What axis is priveleged for rotations?
Vangelis Lympouridis has a tool that works this problem quite well for the dp.kinect.

With jit.openni I have been muddling along using the "torso" as the origin. 
The center of mass (/user coordinate)  is rather jittery.

**Comment by joncorcu** [comment]
Thanks for the answer adrian,

The torso is my origin. I take the difference between the head and the torso and multiplied by 3, so according to Vitrubian proportions that should be users height and the maximum distance between the 2 hands. 

The next step was taking the hand position and subtract the torso, and divide this value by the height. This is not working good enough but i think i am close...

I can´t run dp.kinect beacause i'm working in mac.

**Comment by adrianfreed** [comment]
The head value is the middle of the head not the top so that might be an issue.
Similarly the hand value is not the end of the fingertips.

Building the hand one based on height builds in an assumption that the head is visible. 
My dancers find lots of positions where the head is not visible but the hands and torso are.

I am using Mac also.

**Comment by CarloCattano** [comment]
any news about this concept? im also very interested an im so new to max , any help will be apreciated
