### ISSUE TITLE
Skeleton Output

### ISSUE THREAD

**Issue by ghost** [diablodale/jit.openni#27]
Im sure this is an error with me rather than your external but I cannot get skeleton tracking to work at all. I presume that there is something I need to add to the default .xml config file to make it try to do this but I cant figure it out, and I also cant find any documentation to help from openNI. The picture and depth seem to work in the example max patch, and i followed the install procedure in the wiki, but i absolutely cannot get it to try to detect my skeleton or output anything. I do have a newer kinect (1473) but as the picture and depth seem to be working im not sure thats the problem.
Any ideas where I could start looking to fix this?

**Comment by diablodale** [comment]
Far too little information for me to help you (no patch, no setup info, no mac/win, etc.). I have no reported similar problems on Windows or Mac.
As far as I know, SensorKinect does not support the newer Kinect models. I know of no workaround as the hardware driver was always a hack and the author has not maintained it.

**Comment by ghost** [comment]
The patch was just the example max one that comes with openni, on a mac (OSX 10.8.5), with all of the prerequisites installed as per your instructions and using the supplied xml config file example.
I think what mainly confused me was that i wasnt sure if the skeleton output should work out of the box without a change to the xml config file so i wasnt sure if it was to do with me having a newer kinect or not having the setup right in the first place

**Comment by diablodale** [comment]
The demo patch will fully function with the supplied patch and XML configuration. OpenNI (and therefore jit.openni) does require that you have a hardware driver that works with your hardware. SensorKinect v0.93 is not compatible with newer Kinect hardware or with many Kinect for Windows sensors.

I recommend you try some of the following options:
1) seek a compatible hardware driver on the Mac for your hardware; I am unaware of such for the Kinect on Mac but it could exist.
2) use a Windows computer and dp.kinect which has official Kinect driver support.
3) use different sensor hardware which provides a hardware driver

**Comment by ghost** [comment]
Ah ok, it must be the newer hardware with the SensorKinect driver then (because driverless solutions like synapse work with my kinect). Thanks very much for your time and solution suggestions

**Comment by diablodale** [comment]
AS a caution, synapse also has problems on newer hardware
http://synapsekinect.tumblr.com/post/6307790318/synapse-for-kinect

**Comment by ghost** [comment]
i saw that but it seems to work ok with mine as i gave it a pretty thorough test
