### ISSUE TITLE
jit_openni: XML config initialization open failed (File not found!)

### ISSUE THREAD

**Issue by titsitits** [diablodale/jit.openni#28]
Hello,

I recently tried jit.openni , on Windows 8 64bits, using these features : 

Max 5.1, Jitter 1.7.0 installed
OSC-route ("OpenSoundControl route") object version 1.16 by Matt Wright.
Copyright ) 1999,2000,01,02,03,04,05,06 Regents of the University of California. All Rights Reserved.
jit.openni v0.8.8, Copyright (c) 2012 Dale Phurrough. This program comes with ABSOLUTELY NO WARRANTY.
jit.openni v0.8.8, Licensed under the GNU General Public License v3.0 (GPLv3) available at http://www.gnu.org/licenses/gpl-3.0.html
jit.openni v0.8.8, Compiled and casually tested with OpenNI 1.5.4 (Build 0), NITE 1.5.2 (Build 21)

I tried with all 64bits versions of openNI, sensorkinect, and NITE, and then with all 32bits versions, and I got this problem : 

jit_openni: XML config initialization open failed (File not found!)
dumpout: read jit.openni_debugrec.xml 0
jit_openni: XML config initialization open failed (File not found!)
dumpout: read jit.openni_config.xml 0

What does that mean ?

Thank you for your help

**Comment by diablodale** [comment]
First consider that you must have the 32-bit versions of everything installed. Next, Max 5.1 is too old for me to investigate. Please upgrade to Max 6.x or the most recent version of Max 5.
After that, please try again. If you continue to have problems, please reply here giving explicit repro steps.

**Comment by diablodale** [comment]
closing no repro no reply
