### ISSUE TITLE
hello there diablodale

### ISSUE THREAD

**Issue by angel120280** [diablodale/jit.openni#30]
hi ,
first  of all,  thanks  for  your  excellent  and  truly inspiring work
i  finally managed to install  all of  the necessary items   for  the jit.openni to work properly
at the beginning i had some problems  (it_openni: XML config initialization open failed (Failed to set USB interface!)  but i found some  really useful information here  to solve  this problem

 so now i just  have  i quick question  
recently i started playing  around  with max,  (mind-boggling infinite possibilities for creation)
i'm working  on a tutorial   of  physical  bodies;  depending  on the  bodies position on the universe  they produce  sound
so  ii'm trying to combine this patch with your example  (4_kinect_physics)
i  have  a slight  problem,  
the range of motion of the  bodies that are  control  by the right and left hand  
is quite  narrow  , 
even if  i reduce  the ( world_box scale) ,  still  the (right left hand bodies)  are not  able to interact  with the other  bodies .  i know its quite  trivial  but  we' all  got to start  somewhere.. right..
is there a way to  expand  the range of motion for  the  bodies  control by the right  and left hand?
is there  a way to calibrate the sensor  according  to te world_box _scale?

again, thanks   for  sharing  your knowledge   with  the community

OSX 10.9.2  
MAX 6.0.4
when i tried this i was  about 8 or 9 feet away   from the sensor
cheers 

<pre><code>
----------begin_max5_patcher----------
4321.3oc6cksbihjE8Y6uBB8XOtHx8k4IOyuQGc3.KQISURfF.6Zoit+1mbA
j.YHIkKDB41kKKyhDbySd2uWR8m2dyhGy9dbwhf+cvuGbyM+4s2bi4P5CbS0
92rXaz2WtIpv71VjF+srG+xh6rmpL96klCuq9H6hJW9TR55GxiWVZuvPA.GR
oTjTbW.hgBIHJGcW.SFBjDtdSDHDD7GUWhjUlKo517IHVVeg+bVZYZz1Xy49
O4IQapOS5yaSR2DWZHP3gCl8bY8QAMtHEI+zbQfnPPShNNuZXWMtUu6jMwuD
mWjjk13Reyhnc6Zb3aZ7Qzf0WxLWH1c6OTRp8Pf8GJO9kj5OOwdv+515K+Aj
SgJ2YegQL+gHZ.Tpop0axV903UMu3Kx1EmljtKOtHNsLpr5tr+zqh+bzyaJe
nann84+bzx3d+vcNYbyh04IqxR0DQqOo9v02NEKAUOZzudXvXdGoQ653CWnF
GOW7XTtF0dbi4hfpOYYV1l1mZ+DkhUNJMYaTYbYhkXQf8Wzjs6xSRKacihSi
TWimJVlmsYSqKk8LuzwYVolKWF+sjUkOYtVMgR0aOYW8Tvh8Xzpj0wEksOVY
z5h1GokrYSlrlxnsNtKY01xqeJ.E17DcH1h.hPpZRRhCAp+AUaiQ5izTX8UB
rzlW09YSdkbKp8IZH6BO5B1ASqgs27IJ+wtJVrEedSVjZn7G0uk+51aq23tw
GP2Es7qp4d6+8CYQZY5JjkyzBDNQV1aDYwiNxNYf5yosf0gQVH0vgBafrPkw
mgfV9aDZg8BsjeIl165eioB5+RRY35MgZcmGCAcwQSfgDFABgJkDXXHkigJy
5PHdHEFbwaD6E8h8n2Ja8cSHqsFe28zOJBeLa0OBtuXYzlXE+Ms92A.bpwc.
kGUgLNACYJrV.GhOW.Fc97qBrV4KjxihUA6xJRLFi8S8LGuGbkxAwV3nisyd
0y4pacbvlGdJJckW7qPf4Ob9fnIZzci3pQqfRqqwU3mh1EqTLX9SwNU3IwGT
S.q+c.XWBBkpPrnZ0xp.ujX.Qn1FI.CNCfmM5JTfxCJ6P4Iee7mKLzsW7t1.
vPz5W60YBrnWrA3krdWBzMN8xrsaiSqhdnCn3PDUaRR6K.ByvTe9twnhrmyW
Ve62OpBZOnUg2TljtOBye+fn6QuwmRVspcDc1ffJzgTYCd0qozSln4dRyZeq
mSzLzWZFNenYjOzLc9fyLe4mgyFZtCQqdvY9rgl4dq2.Oe3MnmhdCz7f2.b8
gycHZ0CMCFIZ9fswUlPBhSW9iGVFs7oJxpx2h5bwtnH5k3UOnHAky.ODUp7A
4QkKuEGmnX24Lsij84QdTcbpWmpvgSpaOYhb8lrGi1Tk+682tVDwqFPGeSt8
.Had0xZbtJl.WECAV4HKi0tXBzPDQskvUwDn+StXBbnvTIAzG0S3i5I7lBVR
q.74D+xLEhER3DDmnlVpBZBdTPSZdsii8oo3JRbVSohVcyC6gYBtUPn5gp4N
sJY6h9haEOk4gwKvWHC455zfUHN.RQ57BVMgbxnubBQeJoaz2j8iqI7GGprO
A3XctYAMj.rEN6TmCvfIbNfqowNlCxiV8f0pyLcdHZSx5ziGa52lxjao0Prh
JLoNSm.oCYANXg5S9TodJzpNVenhsYYkO8fhyak5D5inbUTcfCuCX67wzSFj
wJuQ.J9.kCKgHoTJTdl.YLMe.A4J8QiQh2xxSZZr1O1gCRcVnZNLa+qUBaJj
GJpmGjn8yCCWGaA6i5XOX0VIXRnxCRNTqtSYjWVota3hYK3eTL6ggW.eO7BI
zCZQFth1BwGUz9Wqh1XAJDJjTi6TH7AS4CWRaH.8QMseC0zl.g642wpn74Lt
TC+dTYakHwGk11iRa2DhQTdHRssD4S8sg.9+TKvctOE3lvTtWfDPh7PYt8.T
EeTm6wnN2XhHTJoLfVasx8CtxTIk6UgtgPvGU5tClX+q2M4cY8tI9VCHfX9T
3JruUAxv0OWnZcpltBoZw0HUiwWiTM.cUR0WmXs2cMCXFUxdf28Yv7QcsgT7
oWeD7YSu9H7Fm4yKb1m9SRLe5CLg+RgyHflcJLGnOZni2aMzw13hhn0wupiN
xiiV4poNH5Hz.LUXb2EHwgXDkIUwffsk0Wzc+bHHmX6bf5rcNftami9x9v3z
pKcmTxNwHIWDRoLSVHIXo44b50IirE.cpO7rhNAHzoBP2cF.oNxqHt9WmO6w
RZnPBPTM6jZ6tymXSTSBFktDZVfZukbrzcWWIHgbIVfvJlOcksQBjd6NRvRK
rDdQvxNyix3fp+bSXwljkwAHmvE9f9LDBtWgFk6Bsf.4nnQa5X8bouOP21Uo
IOrLK8yIqC+9VmZ2Hb5dDiw2CXP2l.fPz6Ca.VrJ3d0cZ2ykOT70X0MLKU4z
+80aq7EHWwTqOjxqnxswJSFANEZILXHBvPFfjCaXVk5jMDhGEoV1ujTq+681
YeKyVudemNzIDBP3PHAPHHcY.YgDByXJA4TsGWd3ZlGYlop6ejF8OpGPHrOr
xzngiHO3+SQj4YAT.vIZvAgbrTdvVJ2ooTN+hHc9XT55QEc1Vl84+1Avn7JK
T.zkmWo7hQBIL..o3XHtQG1nHlcpnSQx5T0M3MgOpfkJ2WjwNefCU9InjSTZ
XrNoBoLHULn7BYwHHSL5S64AkOEatpN0PvBk.07sxsbgxWS85NfxwHl6o9S0
rEX9Y1ptzyEwkKi23x3tjS1CQbjLDq1VWhIIxIFAuHhGiKFo63mDyOuDs43F
+YHrhIvgDkVErzFpmKv5TCZgO+.qxfGUiO0K.OwGJfDBPbDEMj7FabVFoHuE
CQ2YsVeW6cGU8TQoqx1FHbplBvBQX0+3ZrhtmuZ.bSbQLfeA.HoJnVJiw0qf
ITgLjpvGNaP7g+OF7oobmJ9AOwG10E9zp4x6rytUwlRvBp1EXcG9qG6jW83s
bbi82BRnipYs18vus0Pusc6buNO5kjxernKPDO8NK3.cwRVHSBX5Tbx3rPAS
oYmSbxggu98R3maztQRBVmm87NegGBREXJiq3CEN8LfgtxxoT+IdKOqzYBOZ
gOMrwQbl0MF7cC.8krjTOwGpdQ3QoGCKFJLUF38A9Xy28mjgr.8uJGwgg9BV
pHYALEuDW2bmRWnE8T8zjM+zGU8jJ7Y8O9hPMcE2M.IFEE13SDfb+zGLdoIx
UVhrbNLJRWQJf16IrSaaT90uss+kyn4pgjFJqgJGopctrWf4JysxuVrIYUbt
CffAOLpITSwcwXyiQEE2CFPO4bL6VwbmC2yPzpdwQzx7jS+anj2Egf8aNi9h
hwVdgC1gd8yvXKTA+t.UprDYxflGLMMMB4zmOJ5hXDpgD0YPvRWGwjRmpYZZ
xtRMCg4DnfWDf5Wqrdw+bUzRW0qgq6al5DXzHIq1H4IzdvBvIH4.dCz85njT
eIapTDpqDGCaJ6f9AdQplMojPjtBDhtF.Dw41jQUskNCL2YEKeLJ8q+c.Ehz
YyT+quPUizUAwNq4.4T83hbwKIWesfgyjnKkgHcmPYMqXMkzWOVPXuOZwBaC
CDfCLN9iQAB8OtPIatMg17qT0IJ8x4PtZ6zoAS5IuZshRoagxfZ0Lcrnx3Jm
mD7YLmmBvqS4Ywt33USSBO6S9SuPQ8fdQyxUBOQT7wPqEr6UX7cR+NoQmvU4
IuDGb+yIOrIonLN0Yx8r3BEIMHEyrJ+6zGOx6q93boZ.jGEbuRVeW1JefJ8R
hWMTgclhOr3ho7Z8lGzizmyiOiJvZU0FF8MT0FLapqZy2xx2rRMten4pwyko
3M92j5BaWJPfVkXtaO8Sd4X7R2d5C28SDgk2ZuSlNF8yyddROWmlkTD21QIO
Fz1tpWm9NWiZz6sFB+31r2odYRCoCgvIPAemBTaedSYxtMwAjf6WuwDHZw9k
ujf7rRkVl.asZVlsIKeX7Diq9xPwMmGXTBsaFosoZ3CkCqrY+h43ERYSuAoF
RboYA.reCjMbPpn2qAoBGFeXV1.ny3SQuK0mD+8c4A2adsHMKe6uC9ieiVsI
7vlH0ldHHYyFBxc8KwWjpgelwwWw1g0+LLjUw54N0HuKM4addD2aKCGbu9.G
aMyZF6yY5mR5AwRDz9GoSM4mpXLdTxGuyG+lQsSDMq3VJRsHd358.sKzjUK2
VsBkqo.K+7IwhuDOEr6RV9UmU4oFdH9.OH74S7DO8oIQiPqxi91voyDA7.cf
nyWKXLYohbnrPVmMWalQp9pZS1SV0Ne9YMkoyvHHYRwhG3hzj8H.TNH6B6JS
V5WkiAPO7UiVebLHz6CVFkxE85.oxf984QqRdtvoCR0HT0yuLV5TGL3Rx2T+
oxy9Yb5vqMJMpX7n+M+hFm+VR5pruEr6q4eZY42GTONlgC4BBCvsqy9tTleY
f45G6mSGpazeXTSqJbWfoJ1Xc88OKfuhIOWuL5jWi+A2WU3Af5mCe8d6X9.K
1OefvN0VJuzSGi6ytlBkJhGDepzHT8TMzCxHtnHicfbddh5qKuIX3jVwuReH
5w3gYBrFNqd546gIfdQra91Sxmm8QfdkCvCGuOmsL.i755sU+86wT3kwfHE0
1X31Bb2ER4nTkHxYD4zqRKGibq9g5ljrrXlfcPItgH1PQ+xOmrYrqC1L9agM
CBmX1rmxd4PVOlG.GDXQtSqanfSs.pNgQayVMQbcZ5ocsqdJIs0xk3hGWaKs
mUdUic.kOiBkqQ5sHb.078bRSQ10oYJ3eSRaTsqhhP81ACoCaLA+2rC4FPOj
zbeMnZPH5tFuzjVyydV4As41v.M9ZgremXzW+VWaLQBLW5i2n484wr7Uw4C5
Lzd2SfK7OWvG3JdLZ4WWaFRMun16cKZ1LKV+RS5r2t69U9eY9HsWF2sbbGuP
jVw20wx.rr4JkaeKYp3VK33udoG80K6nuRFXroH5jQQsVJs6gdvSG0H8fbPS
F4v8AcHjoidfiA8rMY0tLkzVwgEoIR85wC0VqfJSYGsKjYZREI2VHdVypuOd
CRBadA5Gcq5Qjs4JX7YkbD9PMvoSj0duHCQQfITIKDMyvHAYtQP9nmUBmL5Q
BlWziOBYxIkZfyFpg6CuCmOczC2G5YBMR6ivNaBmu7Q1hOcxV9LcMc9+x7wg
bCDROAWpjh8tTQqpGJvlWki1kYauLHfgB4XL1tlgJOKNVYFpHeFpmf2iP.Dc
7XUx.MFpU6UMRa5s4YcfhG44TyR64LcRcPsMhoUdZP5gOynG1zQO93Zgg2bZ
Bmfw8kdfSC8v7kdln4KpO7OmlNSDmEJqd.zvPaSJPM+o8dHoMux1klAydmCM
HXeh2leZCQBfEBqVZI3.SZCX1uVYauG0NR4HbHX+CnO57LN8IpP1zECFymj4
vltjcw7wOQ1z4mHaVECF0K6HSmdIpOAERmP7g6K9LM1Qn9v9PmN+Pn9XGwPz
SD9P7kdlH7wGqPFhdhvGjuzCX5nmAk2mNqWTerdQESK8LH9LcVS8Qbe5PGhO
QcPAyP5YZj1I9X8hLgyWd4S9DNegtBoG7DNeAlYzyHDz53QMX14MFZjcwS.x
rQM2duIIFZrOp6wSWrSXeX.vSm0PrWxqfVos8rROfY17kmsXvD0EN9XMDMcZ
6Q9n+.Mg3iORWnIrqo7g8AOcw5hPyL9GnuZePyG5ANYN+h.ypLsAmYRWPuTN
ilv1aZlgO9DJG7z7tiaWq3v1UwFlcQvn8dDh8ghoQgFLG5L3cm2pOlN.G5C4
7VTeXa55nc6dINun5ZZnjEai9hs8tMeGknlwRyNzt4KxieIo98StUe09qa++
.wpVGz.
-----------end_max5_patcher-----------
</code></pre>

**Comment by diablodale** [comment]
Hello. I appreciate your inquiry and my recommendation is to visit the Max forums at http://cycling74.com/forums/ for assistance. The question you are asking is about Max rather than a bug report about jit.openni.

I will volunteer one thing. The /skel and /user messages of jit.openni are in real-world meters (or millimeters). There is no recalibration. Any change of the x,y,z coordinates you want to use in your Max patch will need to be done with objects or math using Max. It has many objects like scale, zmap, multiply, add, subtract, etc.
