### ISSUE TITLE
missing file ?

### ISSUE THREAD

**Issue by yrphilippe** [diablodale/jit.openni#6]
Hi Diablodale,

maybe I'm wrong, but I can't see any jit.openni.mxe in bin directory.

regards,

y

**Comment by diablodale** [comment]
Correct. The compiled binaries continue to be in the Downloads area https://github.com/diablodale/jit.openni/downloads
That is the location for pre-compiled binaries which have passed a minimum bar of testing.

the mxe was removed from the code tree to present a consistent method/location of binary distribution now that we have a cross-platform windows/mac codebase.

Does this resolve your concern?

**Comment by diablodale** [comment]
New binaries have been posted at https://github.com/diablodale/jit.openni/downloads
