### ISSUE TITLE
depth_fov

### ISSUE THREAD

**Issue by aartcore** [diablodale/jit.openni#9]
first: thanks a lot for the development of the object!

I want to get rid of the offset in de depth image, i suppose it is the two float depth_fov parameters. Only the object doesn't recognize the argument as an attribute. 
Is there a way to change this depth_fov so there is no offset in the depth-image anymore. 

Thanks in advance!

**Comment by diablodale** [comment]
Hello. Three things to consider. First, the attribute depth_fov is a read-only attribute. It describes the field of view of the depth camera. This is a fixed physical value determined by the sensor and the glass lens. It cannot be changed; it a hardware designed value.

Second, what do you mean by offset in the depth image? Offset can mean many things.

Last, do you wish to align the colormap and the depthmap? If you wish to align the two images (their matrices), then you can achieve that by configuring the alignment values in the XML configuration file that you load. The  jit.openni_config.xml that is provided with the demo patcher does align the depth and color matrices.

**Comment by aartcore** [comment]
Thanks for the fast response.

I just removed the line:
-AlternativeViewPoint-Image1-/AlternativeViewPoint-

and the so called "offset" is gone.

Thanks that was just what i needed.
